pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

def isIDE = properties.containsKey('android.injected.invoked.from.ide')
		|| (System.getenv("XPC_SERVICE_NAME") ?: "").contains("intellij")
		|| (System.getenv("XPC_SERVICE_NAME") ?: "").contains(".idea")
		|| System.getenv("IDEA_INITIAL_DIRECTORY") != null

println "IntelliJ: ${isIDE}"
